export const USER_VIEW = 'USER:VIEW'
export const USER_CREATE = 'USER:CREATE'
export const USER_UPDATE = 'USER:UPDATE'
export const USER_STATUS = 'USER:STATUS'
export const USER_PASSWORD_RESET = 'USER:PASSWORD:RESET'
export const USER_ASSIGN = 'USER:ASSIGN'

export const ROLE_VIEW = 'ROLE:VIEW'
export const ROLE_CREATE = 'ROLE:CREATE'
export const ROLE_UPDATE = 'ROLE:UPDATE'
export const ROLE_STATUS = 'ROLE:STATUS'
export const ROLE_ASSIGN = 'ROLE:ASSIGN'

export const PERMISSION_VIEW = 'PERMISSION:VIEW'
export const PERMISSION_CREATE = 'PERMISSION:CREATE'
export const PERMISSION_UPDATE = 'PERMISSION:UPDATE'
export const PERMISSION_STATUS = 'PERMISSION:STATUS'

export const AUDIT_VIEW = 'AUDIT:VIEW'
